# Copyright 2021 Siemens AG
# This file is subject to the terms and conditions of the MIT License.  
# See LICENSE file in the top-level directory.

version: '2.4'
services:
  heartbeat:
    image: conntest_heartbeat:0.1
    mem_limit: 300mb
    networks:
      - conntest-net
  sef:
    image: conntest_sef:0.1
    mem_limit: 1000mb
    networks:
      - conntest-net
  conntest_backend:
    build:
      context: ./src/backend_flask
    image: conntest_backend:0.1
    restart: unless-stopped
    mem_limit: 300mb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    networks:
      - conntest-net
  conntest_frontend:
    build:
      context: ./src/frontend_react
    image: conntest_frontend:0.1
    restart: unless-stopped
    mem_limit: 100mb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    networks:
      - conntest-net
    ports:
      - "3000:80"
networks:
  conntest-net:
    name: conntest-net
