# Copyright 2021 Siemens AG
# This file is subject to the terms and conditions of the MIT License.  
# See LICENSE file in the top-level directory.

version: '2.4'
services:
  heartbeat:
    image: conntest_heartbeat:0.1
    mem_limit: 300mb
    networks:
      - ie-databus
    links:
      - zenoh
  # sef:
  #   image: conntest_sef:0.1
  #   mem_limit: 1000mb
  #   networks:
  #     - ie-databus
  #   links:
  #     - zenoh
  conntest_backend:
    build:
      context: ./src/backend_flask
    image: conntest_backend:0.1
    restart: unless-stopped
    mem_limit: 300mb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    networks:
      - ie-databus
  conntest_frontend:
    build:
      context: ./src/frontend_react
    image: conntest_frontend:0.1
    restart: unless-stopped
    mem_limit: 100mb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    networks:
      - ie-databus
    ports:
      - "3000:80"
  evaics:
    image: altertech/eva-ics4:2023053001
    # volumes:
    # - /srv/docker/evaics/etc:/opt/eva4/etc
    # - /srv/docker/evaics/init:/opt/eva4/init
    # - /srv/docker/evaics/runtime:/opt/eva4/runtime
    # - /srv/docker/evaics/log:/opt/eva4/log
    # - /srv/docker/evaics/pvt:/opt/eva4/pvt
    # - /srv/docker/evaics/ui:/opt/eva4/ui
  zenoh:
    image: eclipse/zenoh-bridge-mqtt:latest
    ports:
      - 1883:1883
    networks:
      - ie-databus
networks:
  ie-databus:
    name: ie-databus
